version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CONVEX_URL: "https://convex.zahar.my"
        CONVEX_SELF_HOSTED_URL: "https://convex.zahar.my"
    container_name: air-app
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      PORT: "3000"
      # Set this to your Convex deployment URL (must be https when site is https)
      # Example (Convex Cloud): https://<your-deployment>.convex.cloud
      # Example (self-hosted): https://convex.yourdomain.com
      NEXT_PUBLIC_CONVEX_URL: "https://convex.zahar.my"
    ports:
      - "3000:3000"
    restart: unless-stopped
